=== hmcts/cpp-context-staging-prosecutors-civil/stagingprosecutorscivil-query/stagingprosecutorscivil-query-api/src/raml/json/schema/stagingcivil.submission-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/stagingprosecutorscivil/query/stagingcivil.query.submission-details",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "status": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/definitions.json#/definitions/submissionStatus"
    },
    "type": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/definitions.json#/definitions/submissionType"
    },
    "receivedAt": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "completedAt": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date-time"
    },
    "materialWarnings": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/problem.json"
      }
    },
    "materialErrors": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/problem.json"
      }
    },
    "caseErrors": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/case-problem.json"
      }
    },
    "defendantErrors": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/defendant-problem.json"
      }
    },
    "caseWarnings": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/case-problem.json"
      }
    },
    "defendantWarnings": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/defendant-problem.json"
      }
    },
    "fileName": {
      "description": "The original filename of the uploaded complaints CSV file, when the submission originated from a CSV upload",
      "type": "string"
    },
    "username": {
      "description": "The display name of the user who submitted the complaints CSV file, when the submission originated from a CSV upload",
      "type": "string"
    },
    "prosecutingAuthority": {
      "description": "The resolved short name of the prosecuting authority for the submission, when the submission originated from a CSV upload",
      "type": "string"
    }
  },
  "required": [
    "id",
    "status",
    "type",
    "receivedAt",
    "materialErrors",
    "materialWarnings",
    "caseErrors",
    "defendantErrors",
    "caseWarnings",
    "defendantWarnings"
  ]
}

=== hmcts/cpp-context-staging-prosecutors-civil/stagingprosecutorscivil-query/stagingprosecutorscivil-query-api/src/raml/json/stagingcivil.submission-details.json
{
    "id": "cedb215e-9297-4799-9a4d-5c608eaa4131",
    "status": "SUCCESS_WITH_WARNINGS",
    "type": "PROSECUTION",
    "receivedAt": "2026-08-14T10:15:30.000Z",
    "completedAt": "2026-08-14T10:16:45.000Z",
    "materialWarnings": [],
    "materialErrors": [],
    "caseErrors": [],
    "defendantErrors": [],
    "caseWarnings": [
        {
            "prosecutorCaseReference": "SCIV12345",
            "problems": [
                {
                    "code": "CASE_HEARING_DATE_IN_PAST",
                    "values": [
                        {
                            "key": "hearingDate",
                            "value": "2020-01-01"
                        }
                    ]
                }
            ]
        }
    ],
    "defendantWarnings": [
        {
            "prosecutorDefendantReference": "SCIV12345-D1",
            "problems": [
                {
                    "code": "DEFENDANT_DOB_IN_FUTURE",
                    "values": [
                        {
                            "key": "dateOfBirth",
                            "value": "2050-01-01"
                        }
                    ]
                }
            ]
        }
    ]
}
